image: python

stages:
  - test
  - build
  - deploy

before_script:
  - python --version
  - pip install tox twine wheel

py36-dj22:
  image: python:3.6
  stage: test
  script: tox -e py36-dj22

py37-dj22:
  image: python:3.7
  stage: test
  script: tox -e py37-dj22

py38-dj22:
  image: python:3.8
  stage: test
  script: tox -e py38-dj22

flake8:
  stage: test
  script: tox -e flake8

wheel:
  stage: build
  script: python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/

pypi:
  stage: deploy
  script: twine upload dist/*
  only:
    - tags
